version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmqdemo
    ports:
      - "5672:5672"      # Porta de comunicação da aplicação
      - "15672:15672"    # Porta do painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
